services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: podrace-db-user
            POSTGRES_PASSWORD: podrace-db-password
            POSTGRES_DB: podrace-db
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
